config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resource :users
  resource :questions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get 'show' => 'users#show'
  #get 'users/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user

  validates :text, :user, presence: true

#домашка 49-1
  validates_length_of :text, maximum: 255, message: 'максимум 255 символов'
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  attr_accessor :password

  has_many :questions

  #параметры для паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

#домашка 49-1 begin
  validates_format_of :email, with: /\A[a-z\d_+.\-]+@[[:word:]\-]+(\.[[:word:]\-]+)*\.[[:word:]]{2,4}\Z/i,
                      message: 'Неверный формат email'

  validates_format_of :username, with: /\A\w+\Z/i, message: 'Используйте только латинские буквы, цифры и _'
  validates_length_of :username, maximum: 40, message: 'максимум 40 символов'
#домашка 49-1 end

  before_save :encrypt_password

#домашка 49-2 begin
  before_validation :username_downcase

  def username_downcase
    self.username.downcase!
  end
#домашка 49-2 end

  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST))
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user.present? && user.password_hash == User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Это действие отзывается, когда пользователь заходит по адресу /users
  def index
    # Мы создаем массив из двух болванок пользователей. Для создания фейковой
    # модели мы просто вызываем метод User.new, который создает модель, не
    # записывая её в базу.
    @users = [
        User.new(
            id: 1,
            name: 'Vadim',
            username: 'installero',
            avatar_url: 'https://secure.gravatar.com/avatar/' \
          '71269686e0f757ddb4f73614f43ae445?s=100'
        ),
        User.new(id: 2, name: 'Misha', username: 'aristofun')
    ]
  end

  def new
  end

  def edit
  end

  def show
    @user = User.new(
      name: 'Vadim',
      username: 'installero',
      avatar_url: ''
    )

    @questions = [
        Question.new(text: 'Как дела?', created_at: Date.parse('03.05.2017')),
        Question.new(text: 'Как погода?', created_at: Date.parse('03.05.2017')),
        Question.new(text: 'Который час?', created_at: Date.parse('03.05.2017')),
        Question.new(text: 'Как настроение?', created_at: Date.parse('03.05.2017'))
    ]

    @new_question = Question.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

#домашка 50-1
  def sklonenie(number, krokodil, krokodila, krokodilov)
    # Сначала, проверим входные данные на правильность
    if number == nil || !number.is_a?(Numeric)
      number = 0
    end

    ostatok = number % 10
    ostatok_100 = number % 100

    if ostatok == 1 && ostatok_100 != 11
      return krokodil
    elsif (ostatok >= 2 && ostatok <= 4) && (ostatok_100 < 12 || ostatok_100 > 14 )
      return krokodila
    elsif (ostatok >= 5 && ostatok <= 9) || ostatok == 0 || (ostatok_100 >= 11 && ostatok_100 <= 14)
      return krokodilov
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div class="header">
    <div class="container">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to 'Хорошие вопросы', root_path %></h1>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="container">
     <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса.В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан как в %>
<%# метод ruby объект после ключа (object: @question) %>
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
        <div class="question-answer text-lead">
          <%= question.answer if question.answer.present? %>
        </div>
    <% end %>

    <div class="question-date">
      <%= question.created_at.strftime('%d %b %M:%H') %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж тремя хелперами %>
          <%# link_to — генерирует ссылку %>
          <%# image_tag — генерирует картинку %>
          <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
          <%# Хелпер user_path(user) возвращает относительный путь %>
          <%# страницы пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), users_path(user) %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%# Блок с информацией о пользователей %>
<div class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%# Используем встроенный в rails хелпер link_to %>
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<%# Блок с формой для задавания пользователю вопроса %>
<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%# Мы используем хелпер form_for, принимающий на вход блок erb-кода, %>
      <%# в котором доступна переменная f, содержащая так называемый form %>
      <%# builder, с помощью которого можно делать поля формы для нового %>
      <%# вопроса. %>
      <%= form_for @new_question do |f| %>
          <%# С помощью объекта для создания полей формы, связанной с моделью %>
          <%# @new_question Мы создаем инпуты с нужными полями для формы, %>
          <%# значения будут подставлены rails автоматически. %>
          <%= f.hidden_field :user_id %>

          <div class="form-field">
            <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
            <%= f.text_area :text, class: 'form-textarea' %>
          </div>

          <div class="form-action">
            <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<%# Блок со списком вопросов к пользователю %>
<div class="column-3-4">
  <div class="user-questions buffer-both">

<%#домашка 50-1 begin %>
    <div class="questions_amount">
      <%= "Всего #{@questions.count} #{t('question', count: @questions.count)}" %>
    </div>
<%#домашка 50-1 end %>

    <div class="questions-list">
      <% @questions.each do |question| %>
          <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>